### PR TITLE
[PO-3657] Make tests a required check for some repositories

### PR DESCRIPTION
**Pull request by mbdimitrova**
🚢 This pull request adds a new setting to repositories - **Required checks** 🛡  In order to have an authorised Feature Review, all selected (if any) required checks for the reviewed repositories must have passed :shipit: 

screen shot 2017-09-08 at 14 53 50

Relates:
- [x] JIRA :gem:: https://jira.fundingcircle.com/browse/PO-3657

/cc @FundingCircle/prod-ops, @0mega 🙇‍♀️

### CODE REVIEW

**Comment by sgerrand** [comment]
🙅 Please do not add this feature, for the following reasons:
* GitHub already supports linking external services, like CircleCI, against commits in a pull request
* GitHub already has branch protection, which prevents merges from occurring with configured status checks passing

This feature is duplicating a better implementation which is _both_ already available and being actively used in _every_ repository.

**Comment by popovm** [comment]
@sgerrand You're correct, GitHub already have these checks and restrictions. 👍 
However, they might be omitted by developers with higher privileges, most of the time for a reason, of course. 
We could improve ST by keeping track of such out of the ordinary events. 
What if GitHub notifies ST that not all checks have passed? 💭

**Comment by sgerrand** [comment]
> What if GitHub notifies ST that not all checks have passed? 💭

That's a good alternative. We can get a lot of information from the commit status.

**Comment by sgerrand** [comment]
Note that Shipment Tracker already keeps track of commits which have failed CircleCI builds.

**Comment by popovm** [comment]
Yes, as long as the CI builds(Jenkins or CircleCI) send information about test results to Shipment Tracker, it will save these results.
What it would not do now is triggering a deployment alert.

**Comment by sgerrand** [comment]
> What it would not do now is triggering a deployment alert.

True, but should it? The act of deployment is what triggers evaluation of events which are attached to that commit, such as CircleCI test runs, JIRA ticket statuses, etc.

**Comment by popovm** [comment]
I think Andy Steward would like to enter the discussion, as the idea of this feature came from him 🙂  
It is good if we are on the same page with him on that.

**Pull request closed without merging**
