### PR TITLE
Update env vars when booting locally with heroku settings

### PR DESCRIPTION
**Pull request by dideler**
- Add `GITHUB_REPO_READ_TOKEN` for repo validation

- Add `GITHUB_REPO_STATUS_WRITE_TOKEN` for posting commit statuses

- Use foreman long options for readability

### CODE REVIEW

**Comment by LogaJ** [comment]
Could you also add the JIRA settings currently in our .env.development file?

**Comment by dideler** [comment]
@LogaJ discussed with @0mega and we'll wait until our JIRA work is integrated to see if it's needed in development.

**Comment by 0mega** [comment]
:+1:

**Comment by andistuder** [comment]
Great! Jira infrastructure is in place, so you should be able to include that now.

**Comment by dideler** [comment]
Added JIRA settings plus the option to override any of the values (e.g. if you have a JIRA running locally and would rather use that instance).

**Comment by LogaJ** [comment]
:+1:

**Pull request merged**
