### PR TITLE
fix SimpleCov configuration

### PR DESCRIPTION
**Pull request by andistuder**
load spec helper first
to ensure SipmleCov gets started first thing

no longer use SimpleCov rails profile when running cukes as it caused
issues

### CODE REVIEW

**Comment by andistuder** [comment]
screen shot 2016-04-06 at 10 39 24

**Comment by andistuder** [comment]
ping @FundingCircle/black-bat

**Comment by dideler** [comment]
LGTM 👍 

Back to green coverage 💚

**Comment by 0mega** [comment]
:+1:

**Comment by LogaJ** [comment]
LGTM

**Pull request merged**
