### PR TITLE
Updates to gems

### PR DESCRIPTION
**Pull request by sgerrand**
:information_desk_person: This change updates gems defined by this project to to their current versions.  Key gems that were updated:
* capybara
* delayed_job
* honeybadger
* rails
* rspec
* unicorn

Also includes security updates to:
* rugged
  - https://github.com/blog/1938-vulnerability-announced-update-your-git-clients
* nokogiri
  - http://www.ubuntu.com/usn/usn-2812-1/
  - https://bugzilla.gnome.org/show_bug.cgi?id=746048

### CODE REVIEW

**Comment by sgerrand** [comment]
:wave: @FundingCircle/black-bat: Would you please review these changes.

**Comment by dideler** [comment]
Some of these updates are causing the tests to fail. I haven't taken a close look at the failures yet, but I think we should wait to upgrade rubocop until the trailing comma regression is fixed. <sup>[[1]], [[2]]</sup>

[1]: https://github.com/bbatsov/rubocop/issues/2369#issuecomment-157610801
[2]: https://github.com/bbatsov/rubocop/issues/2448

**Comment by sgerrand** [comment]
> I think we should wait to upgrade rubocop until the trailing comma regression is fixed.

:ok_hand: Popped that commit out. :recycle:

**Comment by sgerrand** [comment]
One of the updates is passing an invalid URI through to `Octokit::Repository.parse_url`, which is causing the cukes to fail.

**Comment by andistuder** [comment]
@sgerrand  yes, the octokit upgrade (4.1 -> 4.2) breaks the app. I could try and fix this in our next sprint starting tomorrow*, or if you want the branch merged quickly, then maybe leave octokit at 4.1. 

* this is probably preferable, but from looking at it, it will need a bit of a refactor to isolate the gem usage to one class.

**Comment by sgerrand** [comment]
> the octokit upgrade (4.1 -> 4.2) breaks the app.

Unfortunately it's not `Octokit` that's the cause of the cukes failing. I reverted the update to octokit and they still fail. I'll try and narrow down the cause later today.

**Comment by andistuder** [comment]
This https://github.com/FundingCircle/shipment_tracker/commit/d2c1e3eac6ef64e2f2c632266dad83c7c0c2ed15 fixes the test for me locally - awaiting CI: https://circleci.com/gh/FundingCircle/shipment_tracker/920

**Comment by sgerrand** [comment]
:heart_eyes_cat: @andistuder 
I've cherry picked in d2c1e3e.

**Comment by andistuder** [comment]
Great. Is there a Jira issue to approve against?  

FYI: I raised https://github.com/FundingCircle/shipment_tracker/issues/81 to fix Octokit.

**Comment by andistuder** [comment]
LGTM

**Comment by sgerrand** [comment]
> Is there a Jira issue to approve against?

@andistuder: :sparkles: Awaiting PO approval.

**Pull request merged**
