### PR TITLE
Add favicon

### PR DESCRIPTION
**Pull request by dideler**
Makes the Shipment Tracker tab a bit easier to find when you have lots of tabs.

screenshot 2016-01-14 18 47 32

Any other suggestions? E.g. :anchor:, :ship:, :shipit:

### CODE REVIEW

**Comment by 0mega** [comment]
LGTM

**Comment by dideler** [comment]
Found it [here](http://www.favicon-generator.org/search/---/Ship). I've emailed the author about usage rights since I couldn't find any on the site.

**Comment by andistuder** [comment]
Like the choice! 
re:license: did you consider searching a ship here: http://www.favicon.cc/

**Comment by dideler** [comment]
> re:license: did you consider searching a ship here: http://www.favicon.cc/ ?

I've searched on that site but couldn't find any good ones :(

**Comment by dideler** [comment]
Found some others that are free to use, choose your favourite

1. screenshot 2016-02-01 19 26 48 [source](https://pixabay.com/en/sailboat-two-master-ship-flag-blue-310410/)
1.  screenshot 2016-02-01 19 35 06 [source](https://openclipart.org/detail/237854/boat)

**Comment by andistuder** [comment]
my vote goes on 2.

On 1 February 2016 at 19:43, Dennis Ideler <notifications@github.com> wrote:

> Found some others that are free to use, choose your favourite
>
>    1. [image: screenshot 2016-02-01 19 26 48]
>    <https://cloud.githubusercontent.com/assets/497458/12728436/c61a6432-c919-11e5-86e4-eadc8488cda4.png>
>    source
>    <https://pixabay.com/en/sailboat-two-master-ship-flag-blue-310410/>
>    2. [image: screenshot 2016-02-01 19 35 06]
>    <https://cloud.githubusercontent.com/assets/497458/12728684/ef0941be-c91a-11e5-9884-89ece111805c.png>
>    source <https://openclipart.org/detail/237854/boat>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FundingCircle/shipment_tracker/pull/87#issuecomment-178147389>
> .
>



-- 
Andi Studer
Senior Software Developer

+44 207 401 9111
andi.studer@fundingcircle.com
71 Queen Victoria Street, London, EC4V 4AY
@FundingCircle <https://twitter.com/FundingCircle>

Funding Circle Limited is authorised and regulated by the Financial Conduct
Authority under firm registration number 635439. Funding Circle is not
covered by the Financial Services Compensation Scheme. Registered in
England (Co. No. 06968588) with registered office at 3 Dorset Rise, London,
EC4Y 8EN.

**Comment by 0mega** [comment]
I like both, but I think 2. is better. 

We can also use ships.... space ships =P
http://findicons.com/icon/178589/rocket?id=179459
http://www.spaceshipsandspice.com/favicon.ico

**Comment by dideler** [comment]
Going with screenshot 2016-02-01 19 35 06

All aboard the shipping ship!

**Pull request merged**
