### PR TITLE
Improve git loop performance

### PR DESCRIPTION
**Pull request by andistuder**
With this change, we only update a repo if the remote head has been updated.

### CODE REVIEW

**Comment by andistuder** [comment]
@dideler @LogaJ @0mega I did a short investigation on the performance optimisation failed and here a fix. Note the actual change in in this commit: https://github.com/FundingCircle/shipment_tracker/commit/da86a0d68e422caa51e68626490db6c3eb9d7f44

**Comment by dideler** [comment]
If we can prove on UAT that this works and is a noticeable speed improvement then :+1: from me.

**Comment by LogaJ** [comment]
didto @dideler's comment.

**Comment by dideler** [comment]
Ideally we extract the logic out of the rake task like we did for the event updater, that way we can also test it since it's an important flow and will make future changes safer to make.

**Comment by 0mega** [comment]
LGTM

**Pull request merged**
