### PR TITLE
Upgrade rails to v4.2.5.1

### PR DESCRIPTION
**Pull request by sgerrand**
:information_desk_person: Upgraded the `rails` gem, as well as its dependencies to mitigate the security vulnerabilities disclosed in http://weblog.rubyonrails.org/2016/1/25/Rails-5-0-0-beta1-1-4-2-5-1-4-1-14-1-3-2-22-1-and-rails-html-sanitizer-1-0-3-have-been-released/

### CODE REVIEW

**Comment by sgerrand** [comment]
:wave: @FundingCircle/black-bat: Would you please review this change.

**Comment by andistuder** [comment]
LGTM

**Comment by 0mega** [comment]
LGTM

**Comment by LogaJ** [comment]
:+1:

**Pull request merged**
